name: Build LaTeX document
on: 
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            datenbank/datenbank.tex
            gui/gui.tex
            internet/internet.tex
            nachhaltigkeit/nachhaltigkeit.tex
            software/software.tex
            sysprog/sysprog.tex
      - name: Move PDF Files
        run: |
      - name: Create Pull Request
            mv datenbank/datenbank.tex
            mv gui/gui.tex
            mv internet/internet.tex
            mv nachhaltigkeit/nachhaltigkeit.tex
            mv software/software.tex
            mv sysprog/sysprog.tex
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Compiled new PDFs
          title: Neue PDFs
          body: |
            Neue PDFs wurden automatisch erzeugt. Mergen, um die neusten PDFs zu haben. 
            Dies ist ein automatischer Pull Request.
          labels: latex, automated pr
          branch: latex-compile
