name: Build LaTeX document
on: 
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
             analysis/analysis.tex
             betriebssysteme/os.tex
             ginf/ginf.tex
             rechnertechnologie/rt.tex
             rechnertechnologie/rt_misc.tex
             wirtshaftsmathe/wirtschaftsmathe.tex
      - name: Move PDF Files
        run: |
          mv analysis.pdf analysis/
          mv os.pdf betriebssysteme/
          mv ginf.pdf ginf/
          mv rt.pdf rt_misc.pdf rechnertechnologie/
          mv wirtschaftsmathe.pdf wirtshaftsmathe/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Compiled new PDFs
          title: Neue PDFs
          body: |
            Neue PDFs wurden automatisch erzeugt. Mergen, um die neusten PDFs zu haben. 
            Dies ist ein automatischer Pull Request.
          labels: latex, automated pr
          branch: latex-compile
